export default {
  ADDING_PRODUCT: 'ADDING_PRODUCT',
  ADD_PRODUCT_ERROR: 'ADD_PRODUCT_ERROR',
  ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
  CHECKING_OUT: 'CHECKING_OUT',
  CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
  CHECKOUT_ERROR: 'CHECKOUT_ERROR'
};
