const SET_ADD_PRODUCT_STATE = 'SET_ADD_PRODUCT_STATE';
const SET_ADD_PRODUCT_ERROR = 'SET_ADD_PRODUCT_ERROR';
const ADD_TO_CART = 'ADD_TO_CART';

export default {
  SET_ADD_PRODUCT_STATE,
  SET_ADD_PRODUCT_ERROR,
  ADD_TO_CART
};
