const SET_ADD_PRODUCT_STATE = 'SET_ADD_PRODUCT_STATE';
const SET_ADD_PRODUCT_ERROR = 'SET_ADD_PRODUCT_ERROR';
const SET_CHECKOUT_STATE = 'SET_ADD_CHECKOUT_STATE';
const SET_CHECKOUT_ERROR = 'SET_CHECKOUT_ERROR';
const ADD_TO_CART = 'ADD_TO_CART';
const CLEAR_CART = 'CLEAR_CART'

export default {
  SET_ADD_PRODUCT_STATE,
  SET_ADD_PRODUCT_ERROR,
  SET_CHECKOUT_STATE,
  SET_CHECKOUT_ERROR,
  ADD_TO_CART,
  CLEAR_CART
};
