export default {
  FETCHING_CURRENT_USER: 'FETCHING_CURRENT_USER',
  FETCH_CURRENT_USER_SUCCESS: 'FETCH_CURRENT_USER_SUCCESS',
  FETCH_CURRENT_USER_ERROR: 'FETCH_CURRENT_USER_ERROR',
  FETCHING_ALL_USERS: 'FETCHING_ALL_USERS',
  FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
  FETCH_ALL_USER_ERROR: 'FETCH_ARTICLE_ERROR',
  FETCHING_SALE_RECORD: 'FETCHING_SALE_RECORD',
  FETCH_SALE_RECORD_SUCCESS: 'FETCH_SALE_RECORD_SUCCESS',
  FETCH_SALE_RECORD_ERROR: 'FETCH_SALE_RECORD_ERROR',
  FETCHING_PRODUCTS: 'FETCHING_PRODUCTS',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_ERROR: 'FETCH_PRODUCTS_ERROR'
};
