const ADD_USER_DATA = 'ADD_USER_DATA';
const ADD_SALE_RECORD = 'ADD_SALE_RECORD';
const ADD_PRODUCTS = 'ADD_PRODUCTS';
const SET_FETCH_ALL_USER_STATE = 'SET_FETCH_ALL_USER_STATE';
const SET_FETCH_ALL_USER_ERROR = 'SET_FETCH_ALL_USER_ERROR';
const SET_FETCH_PRODUCTS_STATE = 'SET_FETCH_PRODUCTS_STATE';
const SET_FETCH_PRODUCTS_ERROR = 'SET_FETCH_PRODUCTS_ERROR';
const SET_FETCH_SALE_RECORD_STATE = 'SET_FETCH_SALE_RECORD_STATE';
const SET_FETCH_SALE_RECORD_ERROR = 'SET_FETCH_SALE_RECORD_ERROR';
const SET_FETCH_CURRENT_USER_STATE = 'SET_FETCH_CURRENT_USER_STATE';
const SET_FETCH_CURRENT_USER_ERROR = 'SET_FETCH_CURRENT_USER_ERROR';

export default {
  ADD_USER_DATA,
  ADD_SALE_RECORD,
  ADD_PRODUCTS,
  SET_FETCH_ALL_USER_STATE,
  SET_FETCH_ALL_USER_ERROR,
  SET_FETCH_PRODUCTS_STATE,
  SET_FETCH_PRODUCTS_ERROR,
  SET_FETCH_SALE_RECORD_STATE,
  SET_FETCH_SALE_RECORD_ERROR,
  SET_FETCH_CURRENT_USER_STATE,
  SET_FETCH_CURRENT_USER_ERROR
};
